config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "consultas#index"
  get "consulta_especifica", to: "consultas#consulta_especifica", as: :consulta_especifica
  get "persona", to: "consultas#persona", as: :persona
  get "planeta", to: "consultas#planeta", as: :planeta
  get "nave", to: "consultas#nave", as: :nave

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/consultas_controller.rb
require "graphql/client"
require "graphql/client/http"

class ConsultasController < ApplicationController

	# Star Wars API example wrapper
	module SWAPI
	  # Configure GraphQL endpoint using the basic HTTP network adapter.
	  HTTP = GraphQL::Client::HTTP.new("https://swapi-graphql-integracion-t3.herokuapp.com/")
	  
	  # Fetch latest schema on init, this will make a network request
	  Schema = GraphQL::Client.load_schema(HTTP)

	  Client = GraphQL::Client.new(schema: Schema, execute: HTTP)

	end

	AllFilmsQuery = SWAPI::Client.parse <<-'GRAPHQL'
	  query {
       allFilms {
       	films {
       	 id
         title
         releaseDate
         director
         producers
         episodeID
       	}
       }
  	  }
	GRAPHQL

	def index
		@result = SWAPI::Client.query(AllFilmsQuery)
	end

	FilmQuery = SWAPI::Client.parse <<-'GRAPHQL'
	  query($id: ID!) {
	   	film(id: $id) {
	   	 id
	     title
	     releaseDate
	     director
	     producers
	     episodeID
	     characterConnection{
	     	characters{
	     		id
	     		name
	     	}
	     }
	     starshipConnection{
	     	starships{
	     		id
	     		name
	     	}
	     }
	     planetConnection{
	     	planets{
	     		id
	     		name
	     	}
	     }
	   	}
  	  }
	GRAPHQL

	def consulta_especifica
		# Pelicula
		@result = SWAPI::Client.query(FilmQuery, variables: { id: params[:id]})
	end

	PersonQuery = SWAPI::Client.parse <<-'GRAPHQL'
	  query($id: ID!) {
	   	person(id: $id) {
	   	 id
	     name
	     birthYear
	     eyeColor
	     gender
	     hairColor
	     height
	     mass
	     skinColor
	     homeworld{
	     	name
	     	id
	     }
	     filmConnection{
	     	films{
	     		id
	     		title
	     	}
	     }
	     starshipConnection{
	     	starships{
	     		id
	     		name
	     	}
	     }
	   	}
  	  }
	GRAPHQL

	def persona
		@result = SWAPI::Client.query(PersonQuery, variables: { id: params[:id]})
	end

	PlanetQuery = SWAPI::Client.parse <<-'GRAPHQL'
	  query($id: ID!) {
	   	planet(id: $id) {
	   	 id
	     name
	     diameter
	     rotationPeriod
	     orbitalPeriod
	     gravity
	     population
	     climates
	     terrains
	     surfaceWater
	     filmConnection{
	     	films{
	     		id
	     		title
	     	}
	     }
	     residentConnection{
	     	residents{
	     		id
	     		name
	     	}
	     }
	   	}
  	  }
	GRAPHQL

	def planeta
		@result = SWAPI::Client.query(PlanetQuery, variables: { id: params[:id]})
	end

	StarshipQuery = SWAPI::Client.parse <<-'GRAPHQL'
	  query($id: ID!) {
	   	starship(id: $id) {
	   		name
	   		model
	   		starshipClass
	   		manufacturers
	   		costInCredits
	   		length
	   		crew
	   		passengers
	   		maxAtmospheringSpeed
	   		hyperdriveRating
	   		MGLT
	   		cargoCapacity
	   		consumables
	   		pilotConnection{
	   			pilots{
	   				name
	   				id
	   			}
	   		}
	   		filmConnection{
	   			films{
	   				id
	   				title
	   			}
	   		}
	   	}
	   }
	GRAPHQL

	def nave
		@result = SWAPI::Client.query(StarshipQuery, variables: { id: params[:id]})
	end
end

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = StarWarsGraphQLSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue => e
    raise e unless Rails.env.development?
    handle_error_in_development e
  end

  private

  # Handle form data, JSON body, or a blank value
  def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      if ambiguous_param.present?
        ensure_hash(JSON.parse(ambiguous_param))
      else
        {}
      end
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { error: { message: e.message, backtrace: e.backtrace }, data: {} }, status: 500
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consultas_helper.rb
module ConsultasHelper
end

app/views/consultas/consulta_especifica.html.erb
<center><h1>Film name: <%= @result.data.film.title %></h1></center>

<h4>Release date: <%= @result.data.film.release_date %></h4>
<h4>Director: <%= @result.data.film.director %></h4>
<h4>Producers:</h4>
<ul>
	<% @result.data.film.producers.each do |producer| %>
		<li><%= producer %></li>
	<% end %>
</ul>
<h4>Episode id: <%= @result.data.film.episode_id %></h4>


<table class="table">
	<h2>Characters</h2>
	<tbody>
		<% @result.data.film.character_connection.characters.each do |character| %>
			<tr><td><%= link_to character.name, persona_path(id: character.id) %></td></tr>
		<% end %>
	</tbody>
</table>

<table class="table">
	<h2>Starships</h2>
	<tbody>
		<% @result.data.film.starship_connection.starships.each do |starship| %>
			<tr><td><%= link_to starship.name, nave_path(id: starship.id) %></td></tr>
		<% end %>
	</tbody>
</table>

<table class="table">
	<h2>Planets</h2>
	<tbody>
		<% @result.data.film.planet_connection.planets.each do |planet| %>
			<tr><td><%= link_to planet.name, planeta_path(id: planet.id) %></td></tr>
		<% end %>
	</tbody>
</table>

app/views/consultas/index.html.erb
<h1>Star wars</h1>

<table class="table">
	<thead>
		<th>Nombre</th>
		<th>Ano de Lanzamiento</th>
		<th>Director</th>
		<th>Productor/es</th>
		<th>Numero de episodio</th>
	</thead>
	<tbody>
		<% @result.data.all_films.films.each do |film| %>
			<tr>
				<td><%= link_to film.title, consulta_especifica_path(id: film.id) %></td>
				<td><%= film.release_date[0..3] %></td>
				<td><%= film.director %></td>
				<td><%= film.producers.join(", ") %></td>
				<td><%= film.episode_id %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/consultas/nave.html.erb
<center><h1>Starship: <%= @result.data.starship.name %></h1></center>

<h4>Model: <%= @result.data.starship.model %></h4>

<h4>Starship class: <%= @result.data.starship.starship_class %></h4>

<h4>Manufacturers</h4>
<ul>
	<% @result.data.starship.manufacturers.each do |manufacturer| %>
		<li><%= manufacturer %></li>
	<% end %>
</ul>

<h4>Cost in credits: <%= @result.data.starship.cost_in_credits %></h4>

<h4>Length: <%= @result.data.starship.length %></h4>

<h4>Crew: <%= @result.data.starship.crew %></h4>

<h4>Passengers: <%= @result.data.starship.passengers %></h4>

<h4>Max atmosphering speed: <%= @result.data.starship.max_atmosphering_speed %></h4>

<h4>Hyperdrive rating: <%= @result.data.starship.hyperdrive_rating %></h4>

<h4>MGLT: <%= @result.data.starship.mglt %></h4>

<h4>Cargo capacity: <%= @result.data.starship.cargo_capacity %></h4>

<h4>Consumables: <%= @result.data.starship.consumables %></h4>

<table class="table">
	<h2>Films</h2>
	<thead>
		<th>Film name</th>
	</thead>
	<tbody>
		<% @result.data.starship.film_connection.films.each do |film| %>
			<tr><td><%= link_to film.title, consulta_especifica_path(id: film.id) %></td></tr>
		<% end %>
	</tbody>
</table>

<table class="table">
	<h2>Pilots</h2>
	<thead>
		<th>Pilot name</th>
	</thead>
	<tbody>
		<% @result.data.starship.pilot_connection.pilots.each do |person| %>
			<tr><td><%= link_to person.name, persona_path(id: person.id) %></td></tr>
		<% end %>
	</tbody>
</table>

app/views/consultas/persona.html.erb
<center><h1>Character: <%= @result.data.person.name %></h1></center>

<h4>Birth year: <%= @result.data.person.birth_year %></h4>

<h4>Eye color: <%= @result.data.person.eye_color %></h4>

<h4>Gender: <%= @result.data.person.gender %></h4>

<h4>Hair color: <%= @result.data.person.hair_color %></h4>

<h4>Height: <%= @result.data.person.height %> </h4>

<h4>Mass: <%= @result.data.person.mass %></h4>

<h4>Skin color: <%= @result.data.person.skin_color %></h4>

<h4>Homeworld: <%= link_to @result.data.person.homeworld.name, planeta_path(id: @result.data.person.homeworld.id) %></h4>

<table class="table">
	<h2>Films</h2>
	<tbody>
		<% @result.data.person.film_connection.films.each do |film| %>
			<tr><td><%= link_to film.title, consulta_especifica_path(id: film.id) %></td></tr>
		<% end %>
	</tbody>
</table>

<table class="table">
	<h2>Starships</h2>
	<tbody>
		<% @result.data.person.starship_connection.starships.each do |starship| %>
			<tr><td><%= link_to starship.name, nave_path(id: starship.id) %></td></tr>
		<% end %>
	</tbody>
</table>

app/views/consultas/planeta.html.erb
<center><h1>Planet: <%= @result.data.planet.name %></h1></center>

<h4>Diameter: <%= @result.data.planet.diameter %></h4>

<h4>Rotation period: <%= @result.data.planet.rotation_period %></h4>

<h4>Orbital Period: <%= @result.data.planet.orbital_period %></h4>

<h4>Gravity: <%= @result.data.planet.gravity %></h4>

<h4>Population: <%= @result.data.planet.population %></h4>

<h4>Climates:</h4> 
<ul>
  <% @result.data.planet.climates.each do |clima|%> </h4>
  	<li><%= clima %></li>
  <% end %>
</ul>

<h4>Terrains:</h4>
<ul>
	<% @result.data.planet.terrains.each do |terreno| %>
		<li><%= terreno %></li>
	<% end %>
</ul>

<h4>Surface water: <%= @result.data.planet.surface_water %></h4>

<table class="table">
	<h2>Films</h2>
	<thead>
		<th>Film name</th>
	</thead>
	<tbody>
		<% @result.data.planet.film_connection.films.each do |film| %>
			<tr><td><%= link_to film.title, consulta_especifica_path(id: film.id) %></td></tr>
		<% end %>
	</tbody>
</table>

<table class="table">
	<h2>Characters</h2>
	<thead>
		<th>Character name</th>
	</thead>
	<tbody>
		<% @result.data.planet.resident_connection.residents.each do |person| %>
			<tr><td><%= link_to person.name, persona_path(id: person.id) %></td></tr>
		<% end %>
	</tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StarWarsGraphQL</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <%= link_to "Home", root_url %>
    </div>
    <%= yield %>
  </body>
</html>